services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ./home/lera/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ./home/lera/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge
